# Generated by Django 4.1.1 on 2022-12-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_added',
        ),
    ]
