# Generated by Django 4.1.4 on 2022-12-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_app', '0003_alter_borrow_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='currentstatus',
            field=models.BooleanField(default=False, verbose_name='currentstatus'),
        ),
    ]
