# Generated by Django 4.1.4 on 2022-12-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_app', '0004_alter_borrow_currentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='currentstatus',
            field=models.BooleanField(default=False),
        ),
    ]
