# Generated by Django 4.1.4 on 2022-12-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_app', '0006_alter_borrow_borrower_alter_borrow_date_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='delevoper',
            new_name='developer',
        ),
    ]
